language: erlang
otp_release:
  - 18.0
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R16B
  - R15B03
  - R15B02

env:
  - PATH=$HOME/.cache/rebar3/bin/:$PATH

before_script:
  - curl -O -L https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - ./rebar3 update

script: "rm -rf deps ebin test/*.beam logs && ./rebar3 compile"

branches:
  only:
    - master
